spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID_HERE
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET_HERE
spring.security.oauth2.client.registration.google.scope=profile,email

# H2 Ma'lumotlar bazasi sozlamalari (Fayl ko'rinishida doimiy saqlaydi)
spring.datasource.url=jdbc:h2:file:./data/demo_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate jadvallarni o'zi avtomat yaratishi uchun qoida
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}